---
# tasks file for vector-role
- name: Create group vector
  ansible.builtin.group:
    name: vector
    state: present
  become: true

- name: Create user vector
  ansible.builtin.user:
    name: vector
    groups: vector
    shell: /sbin/nologin
    create_home: false
    append: true
    comment: "Vector nologin User"
    state: present
  become: true

- name: Create directrory for vector "{{ vector_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: vector
    group: vector
    mode: 0755
    state: directory
  with_items:
    - "{{ vector_dir }}"
    - "/etc/vector"
    - "/var/lib/vector"

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"

- name: Extract vector in the installation directory
  become: true
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}"
    creates: false
    extra_opts: ['--strip-components=2']

- name: Create a symbolic link vector
  ansible.builtin.file:
    src: "{{ vector_dir }}/bin/vector"
    dest: /usr/bin/vector
    state: link

- name: Create service vector
  become: true
  template:
    src: templates/vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    backup: true

- name: Create default/vector
  become: true
  template:
    src: templates/vector.default.j2
    dest: /etc/default/vector
    mode: 0644
    backup: true

- name: Create vector.toml
  become: true
  template:
    src: templates/vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: 0644
    backup: true
  notify: Start vector service

- name: Remove vector packages distribs
  ansible.builtin.file:
    path: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    state: absent
  tags:
    - for_delete
    - never
