# Molecule managed

FROM docker.io/monolithprojects/systemd-centos8:latest

ENV ANSIBLE_USER ansible
ENV DEPLOY_GROUP deployer
ENV SUDO_GROUP wheel
ENV container docker

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
dnf update libmodulemd -y && dnf update -y --nobest &&  dnf -y install python3 sudo python3-devel python*-dnf \
bash curl iproute systemd systemd-sysv systemd-container.x86_64 initscripts && dnf clean all && ln -s /lib/systemd/systemd /bin/systemd

RUN if [ $(command -v apt-get) ]; then export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3 sudo bash curl ca-certificates iproute2 python3-apt aptitude && apt-get clean && rm -rf /var/lib/apt/lists/*; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash curl iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash curl iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 sudo bash curl iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash curl ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 sudo bash curl ca-certificates iproute2 && xbps-remove -O; fi

RUN curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py > /usr/bin/systemctl \
&& chmod u+x /usr/bin/systemctl && mkdir -p /run/systemd/system

CMD /usr/bin/systemctl