---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Copy systemctl.py file
      copy:
        src: "../resources/systemctl.py"
        dest: "/bin/systemctl"
    - name: Create directory
      file:
        name: "/run/systemd/system/"
        state: "directory"

  tasks:
    - name: "Include vector-role"
      include_role:
        name: "vector-role"
