---
- name: Converge
  hosts: all
#
#  pre_tasks:
#    - name: Copy systemcrl.py file
#      copy:
#        src: "../resources/systemctl.py"
#        dest: "/bin/systemctl"
#    - name: Package
#      package:
#        name: "python"
#    - name: Create directory
#      file:
#        name: "/run/systemd/system/"
#        state: "directory"
#    - name: Stop dbus
#      service:
#        name: "dbus.service"
#        state: "stopped"

  tasks:
    - name: "Include vector-role"
      include_role:
        name: "vector-role"
