---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    dockerfile: ../resources/Dockerfile_jessie.j2
<<<<<<< HEAD
#    pre_build_image: true
=======
    pre_build_image: false
>>>>>>> refs/remotes/origin/main
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
<<<<<<< HEAD
      - DAC_READ_SEARCH
    tmpfs:
      - /run
      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
=======
    tmpfs:
      - /run
      - /tmp
>>>>>>> refs/remotes/origin/main
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
