---
- name: Converge
  hosts: all
#  pre_tasks:
#    - name: Copy systemcrl.py file
#      copy:
#        src: "../systemctl.py"
#        dest: "/usr/bin/systemctl"
#    - name: Package
#      package:
#        name: "python"
#    - name: Create dicectory
#      file:
#        name: "/run/systemd/system/"
#        state: "directory"
#    - name: Stop dbus
#      service:
#        name: "dbus.service"
#        state: "stopped"

  tasks:
    - name: 'Apply Vector Role'
      include_role:
        name: vector-role
